name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: rustfmt, clippy

      - name: Run Rustfmt
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: ./do.sh clippy -- -D warnings -D clippy::dbg_macro

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly

      - name: Run Tests
        run: ./do.sh test

  e2e-test:
    # if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly

      - name: BPF build
        run: ./do.sh build

      - name: Run E2E Tests
        run: ./do.sh e2e-test
